// <auto-generated />
namespace DmD.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedmaps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedmaps));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261323414_Added maps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
